### ISSUE TITLE
"Couldn't Check in : Boarding Pass can be obtained..."

### ISSUE THREAD

**Issue by rtmill22** [pyro2927/SouthwestCheckin#9] opened 2017-09-28 23:23 UTC
Has there been a fix for this issue? This code worked great prior to their reservation system change in May and ever since it spits out a different number of these errors each time. I wonder if there is an API for the desktop version of the site that can be used?

**Comment by pyro2927** [comment] 2017-12-27 19:05
Closing as a duplicate of #11, working on a fix now, 90% there, just need to test with new API endpoints for a checkin I'll be making tomorrow.

**Closed by pyro2927** 2017-12-27 19:05 UTC
